# Book settings
title: BigBytes Meta2Data
author: Zivko Juznic-Zonta
copyright: "CC0 2021"
logo: icon.svg
only_build_toc_files: true
exclude_patterns: [
  _build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", data, out]

# Execution settings
execute:
  execute_notebooks: "off"

# Add extra data sources (not working since ignores toc tree files)
#sphinx:
#  config:
#    html_extra_path: ['raw', 'processed']