name: metadata
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - tqdm
  - requests
  - bs4
  - paramiko
#  - psycopg2
# Pandas and co.
  - pandas
  - pyarrow
  - matplotlib
# netCDF datasets
#  - xarray
#  - dask
#  - h5netcdf
#  - netcdf4
#  - cartopy
#  - cdsapi
# Pip installs
#  - pip
#  - pip:
#    sodapy